### ISSUE TITLE
Different "path"-dict-key-names on localized systems

### ISSUE THREAD

**Issue by donnerbrenn** [Shizmob/smol#7]
Hi there, 

I'm on a german arch system. I get a key-error when I run the freshly cloned project.

```
mkdir: Verzeichnis 'obj/' angelegt
cc -flto -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "test/hello.c" -o "obj/hello.lto.o"
cc -flto -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "rt/crt1.c" -o "obj/crt1.lto.o"
cc -m64 -nostartfiles -nostdlib -r -o "obj/hello.start.o" obj/hello.lto.o obj/crt1.lto.o
python3 src/smol.py  -lc -lSDL2 -lX11  "obj/hello.start.o" "obj/symbols.hello.start.asm"
Traceback (most recent call last):
  File "src/smol.py", line 78, in <module>
    main()
  File "src/smol.py", line 61, in main
    spaths = args.libdir + paths['libraries']
KeyError: 'libraries'
make: *** [Makefile:77: obj/symbols.hello.start.asm] Fehler 1
```

I figured out, this lines, produced the errors:

```
src/smol.py:    spaths = args.libdir + paths['libraries']
src/smol.py:    libraries=paths['libraries']
```

So I printed out the paths-dict-keys on my system and found out, the keynames are localized too... (I have the key "Bibliotheken", what's the german word for "libraries", if Ichange the script to 'Bibliotheken' everything just works right)

I'm not a python-wizard, so I would come up with a fix, if I could, but I think, other people might be on a localized system too... (I tried it with a german Ubuntu on a virtual system, there are no problems there.)

**Comment by PoroCYon** [comment]
Sorry for not noticing this any earlier.

I have an ugly fix ready, but I'd rather force GCC to output the proper key names. Can you try running `LANG=C gcc -print-search-dirs`, or maybe `LANG=LANG=en_US.UTF-8 gcc -print-search-dirs` and tell me if the output is correct?

**Comment by donnerbrenn** [comment]
Hi PoroCYon

No need for an excuse....

Doesn't seem to bring, what we are looking for... Or i just don't understand, what exactly you are looking for. ;)

➜  ~ LANG=C gcc -print-search-dirs
install: /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/
programs: =/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/
libraries: =/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/lib/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../x86_64-pc-linux-gnu/8.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../lib/:/lib/x86_64-pc-linux-gnu/8.3.0/:/lib/../lib/:/usr/lib/x86_64-pc-linux-gnu/8.3.0/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../:/lib/:/usr/lib/

**Comment by PoroCYon** [comment]
Alright, that seems to work. Can you try out the patches in the above PR? If so, I'll merge them.

**Comment by donnerbrenn** [comment]
Of course. Seems to work. Did a fresh clone, applied the patches aaaaaand. Success! ;)

The error messages are gone, everything compiles fine. The *-crt examples are running.

```
➜  smol git:(master) make
cc -flto -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "test/hello.c" -o "obj/hello.lto.o"
cc -flto -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "rt/crt1.c" -o "obj/crt1.lto.o"
cc -m64 -nostartfiles -nostdlib -r -o "obj/hello.start.o" obj/hello.lto.o obj/crt1.lto.o
python3 src/smol.py  -lc -lSDL2 -lX11  "obj/hello.start.o" "obj/symbols.hello.start.asm"
nasm -I rt/ -f elf64 -DUSE_INTERP -DNO_START_ARG -DUNSAFE_DYNAMIC -DUSE_DNLOAD_LOADER  obj/symbols.hello.start.asm -o obj/stub.hello.start.o
cc -Wl,-Map=bin/hello-crt.map -m64 -T ld/link.ld -Wl,--oformat=binary -m64 -nostartfiles -nostdlib obj/hello.start.o obj/stub.hello.start.o -o "bin/hello-crt"
cc -flto -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "test/sdl.c" -o "obj/sdl.lto.o"
cc -m64 -nostartfiles -nostdlib -r -o "obj/sdl.start.o" obj/sdl.lto.o obj/crt1.lto.o
rt/crt1.c:4:12: Warnung: Typ von »main« passt nicht zur ursprünglichen Deklaration [-Wlto-type-mismatch]
 extern int main(int argc, char* argv[]);
            ^
test/sdl.c:4:5: Anmerkung: unverträgliche Typen in Parameter 1
 int main(void) {
     ^
test/sdl.c:4:5: Anmerkung: Typ »void« sollte Typ »int« entsprechen
test/sdl.c:4:5: Anmerkung: »main« wurde vorher hier deklariert
python3 src/smol.py  -lc -lSDL2 -lX11  "obj/sdl.start.o" "obj/symbols.sdl.start.asm"
nasm -I rt/ -f elf64 -DUSE_INTERP -DNO_START_ARG -DUNSAFE_DYNAMIC -DUSE_DNLOAD_LOADER  obj/symbols.sdl.start.asm -o obj/stub.sdl.start.o
cc -Wl,-Map=bin/sdl-crt.map -m64 -T ld/link.ld -Wl,--oformat=binary -m64 -nostartfiles -nostdlib obj/sdl.start.o obj/stub.sdl.start.o -o "bin/sdl-crt"
cc -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "test/flag.c" -o "obj/flag.o"
test/flag.c: In Funktion »_start«:
test/flag.c:47:27: Warnung: ISO-C verbietet leere Initialisierungsklammern [-Wpedantic]
   static XGCValues vals = {};
                           ^
python3 src/smol.py  -lc -lSDL2 -lX11  "obj/flag.o" "obj/symbols.flag.asm"
nasm -I rt/ -f elf64 -DUSE_INTERP -DNO_START_ARG -DUNSAFE_DYNAMIC -DUSE_DNLOAD_LOADER  obj/symbols.flag.asm -o obj/stub.flag.o
cc -Wl,-Map=bin/flag.map -m64 -T ld/link.ld -Wl,--oformat=binary -m64 -nostartfiles -nostdlib obj/flag.o obj/stub.flag.o -o "bin/flag"
./rmtrailzero.py "bin/flag" "obj/flag" && mv "obj/flag" "bin/flag" && chmod +x "bin/flag"
cc -Wall -Wextra -Wpedantic -std=gnu11 -nostartfiles -fno-PIC -Os -fno-plt -fno-stack-protector -fno-stack-check -fno-unwind-tables -fno-asynchronous-unwind-tables -fomit-frame-pointer -ffast-math -no-pie -fno-pic -fno-PIE -m64 -march=core2 -ffunction-sections -fdata-sections -fno-plt  -m64 -I/usr/include/SDL2 -D_REENTRANT  -c "test/hello-_start.c" -o "obj/hello-_start.o"
python3 src/smol.py  -lc -lSDL2 -lX11  "obj/hello-_start.o" "obj/symbols.hello-_start.asm"
nasm -I rt/ -f elf64 -DUSE_INTERP -DNO_START_ARG -DUNSAFE_DYNAMIC -DUSE_DNLOAD_LOADER  obj/symbols.hello-_start.asm -o obj/stub.hello-_start.o
cc -Wl,-Map=bin/hello-_start.map -m64 -T ld/link.ld -Wl,--oformat=binary -m64 -nostartfiles -nostdlib obj/hello-_start.o obj/stub.hello-_start.o -o "bin/hello-_start"
./rmtrailzero.py "bin/hello-_start" "obj/hello-_start" && mv "obj/hello-_start" "bin/hello-_start" && chmod +x "bin/hello-_start"
➜  smol git:(master) 
```

**Comment by PoroCYon** [comment]
Alright, I'll merge it.

Btw, in the future, can you enclose the console output in three backticks? (Like so:

> ` ``` `
> `code`
> ` ``` `

(I edited your comments already `:P`)
